version: '2'

services:
  postgres:
    container_name: resource-adaptor-pg
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'

  redis:
    image: 'redis'
    container_name: resource-adaptor-redis

  resource-adaptor:
    container_name: resource-adaptor
    depends_on:
      - 'postgres'
    build: .
    ports:
      - 3002:3000
    volumes:
      - '.:/resource-adaptor'
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_HOST: 'resource-adaptor-pg'
      POSTGRES_PORT: 5432
      CATALOGUER_HOST: 'resource-cataloguer:3000'
      ADAPTOR_HOST: 'resource-adaptor:3000'
      RABBITMQ_HOST: 'rabbitmq'
      KONG_URI: 'http://kong:8001'
      SELF_HOST: 'resource-adaptor:3000'
      REGISTER_METHOD: 'target'

  sidekiq:
    container_name: resource-adaptor-sidekiq
    links:
      - 'postgres'
      - 'redis'
    build: .
    command: bash -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - '.:/resource-adaptor'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_HOST: 'resource-adaptor-pg'
      POSTGRES_PORT: 5432
      CATALOGUER_HOST: 'resource-cataloguer:3000'
      ADAPTOR_HOST: 'resource-adaptor:3000'
      RABBITMQ_HOST: 'rabbitmq'
      RAILS_ENV: 'development'
      KONG_URI: 'http://kong:8001'
      SELF_HOST: 'resource-adaptor:3000'
      REGISTER_METHOD: 'none'

networks:
  default:
    external:
      name: platform 
